export { addDts } from "./utils/add-dts.js";
export { addVirtualImport } from "./utils/add-virtual-import.js";
export { addVitePlugin } from "./utils/add-vite-plugin.js";
export { createResolver } from "./utils/create-resolver.js";
export { defineIntegration } from "./utils/define-integration.js";
export { hasIntegration } from "./utils/has-integration.js";
export { watchIntegration } from "./utils/watch-integration.js";
export { addIntegration } from "./utils/add-integration.js";
export { addDevToolbarPlugin } from "./utils/add-devtoolbar-plugin.js";